FROM node:alpine
 
WORKDIR /usr/src/app

COPY . .

RUN npm install
RUN npm install @fortawesome/react-fontawesome @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/free-regular-svg-icons @fortawesome/free-brands-svg-icons

 
EXPOSE 5173